Task 6
CherniyKot/formal-lang-course pull request #5
Opened 2023-03-31 23:12 UTC by CherniyKot

2023-04-01 11:14 UTC, rustam-azimov requested changes

2023-04-01 11:14 UTC, rustam-azimov commented on project/cfg_utils.py
> +    cfg = cfg.remove_useless_symbols()
Эти две строки лучше перенести в начало

2023-04-01 12:49 UTC, CherniyKot commented
Отладил таск 4, кстати, теперь работает

2023-04-02 08:52 UTC, rustam-azimov approved these changes

2023-04-04 21:54 UTC, merged